# This file is a Helm values file for the crossplane-fn-mcoidc chart.
#
# To learn more about how to configure your app on your cluster
# and override the default values in here, visit:
#
#   https://docs.giantswarm.io/tutorials/fleet-management/app-platform/app-configuration/#basic-values-merging-example
#
image:
  name: "giantswarm/crossplane-fn-mcoidc"
  tag: ""
registry:
  domain: gsoci.azurecr.io

function:
  name: function-mcoidc
  skipDependencyResolution: true

runtimeConfig:
  name: xfn-mcoidc
  namespace: crossplane
  debug: false
  awsRegion: ""

composition:
  name: mcoidc-composition
  kclFunctionRef: function-kcl
  autoReadyFunctionRef: function-auto-ready
