version: 2.1

orbs:
  architect: giantswarm/architect@5.13.1

workflows:
  build-workflow:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - builddocker:
          context:
            - architect
          filters:
            tags:
              only: /^v.*/

jobs:
  builddocker:
    machine:
      image: ubuntu-2204:edge
    steps:
      - checkout
      - run:
          name: "Push to gsoci"
          command: |
            REGISTRY_SERVER=gsoci.azurecr.io
            REGISTRY=${REGISTRY_SERVER}/giantswarm
            echo "$ACR_GSOCI_PASSWORD" | docker login --username $ACR_GSOCI_USERNAME --password-stdin ${REGISTRY_SERVER}
            [ -z "${CIRCLE_TAG}" ] && CIRCLE_TAG=v0.0.31-dev

            curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh

            docker buildx build . -t ${REGISTRY}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}

            echo "triggering : ./crossplane xpkg build -f pkg/package/ --embed-runtime-image=${REGISTRY}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}"
            ./crossplane xpkg build -f pkg/package/ --embed-runtime-image=${REGISTRY}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}

            cd pkg/package/
            ls
            echo "triggering : ./crossplane xpkg push ${REGISTRY}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}"
            ../../crossplane xpkg push ${REGISTRY}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}

            echo "Pushed to ${REGISTRY}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}"
