apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mcoidc-composition
spec:
  compositeTypeRef:
    apiVersion: crossplane.giantswarm.io/v1
    kind: MCOIDC
  mode: Pipeline
  pipeline:
  - step: mcoidc-discovery
    functionRef:
      name: function-mcoidc
    input:
      apiVersion: mcoidc.fn.giantswarm.io
      kind: Input
      metadata:
        namespace: crossplane
      spec:
        awsAccountsPatchToRef: status.awsAccounts
