apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mcoidc-composition
spec:
  compositeTypeRef:
    apiVersion: crossplane.giantswarm.io/v1
    kind: MCOIDC
  mode: Pipeline
  pipeline:
  - step: mcoidc-discovery
    functionRef:
      name: function-mcoidc
    input:
      apiVersion: mcoidc.fn.giantswarm.io
      kind: Input
      metadata:
        namespace: crossplane
      spec:
        awsAccountsPatchToRef: status.awsAccounts
        name: spec.name
  - step: render-resources
    functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLRun
      metadata:
        name: irsa
      spec:
        target: Resources
        source: |
          # ---------------------------------------------------------------------------
          # Input shorthands
          # ---------------------------------------------------------------------------
          oxr  = option("params")?.oxr          # Observed  Composite Resource (XR)
          dxr  = option("params")?.dxr          # Desired   Composite Resource (XR)
          ocds = option("params")?.ocds or {}   # Observed  Composed Resources map

          # ---------------------------------------------------------------------------
          # Common variables extracted from the XR                                                       
          # ---------------------------------------------------------------------------
          composition_name = oxr?.metadata?.name or ""
          region        = oxr?.spec?.region or ""
          domain        = oxr?.spec?.domain or ""
          # Whether the deployment region is in mainland China (e.g. cn-north-1, cn-northwest-1)
          is_china_region = region.startswith("cn-")

          # ---------------------------------------------------------------------------
          # Existing resources status
          # ---------------------------------------------------------------------------
          existing_aws_accounts = oxr?.status?.awsAccounts or []

          # ---------------------------------------------------------------------------
          # Managed resources
          # ---------------------------------------------------------------------------
          _resources = []
          
          for aws_account in existing_aws_accounts:
            # OpenID Connect Provider
            _oidc_client_id_list = ["sts.amazonaws.com"]
            _oidc_thumbprint_list = ["06b25927c42a721631c1efd9431e648fa62e1e39"]
            _oidc_url = "https://irsa.${domain}"
            if is_china_region:
              _oidc_client_id_list = ["sts.amazonaws.com.cn"]
              _oidc_thumbprint_list = ["9e99a48a9960b14926bb7f3b02e22da2b0ab7280"]
              _oidc_url = "https://s3.${region}.amazonaws.com.cn/${bucket_name}"

            _oidc_provider = {
                apiVersion = "iam.aws.upbound.io/v1beta1"
                kind       = "OpenIDConnectProvider"
                metadata.name = "${composition_name}-oidc"
                metadata.annotations = {}
                spec = {
                    providerConfigRef.name = aws_account.providerConfigRef
                    forProvider = {
                        url            = _oidc_url
                        clientIdList   = _oidc_client_id_list
                        thumbprintList = _oidc_thumbprint_list
                    }
                }
            }
            _resources.append(_oidc_provider)
          
          items = _resources
